server:
  port: 4000
  
---
hystrix:  
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
                        
---                        
management:
  port: 8081
  #address: localhost
  security:
    enabled: false
    
    
 
#security:
#  user: 
#    name: admin
#    password: admin
#    role: SUPERUSER
  
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
  instance:
    preferIpAddress: false

---

spring:
  application:
    name: com-item-item
  datasource:
    initialize: true
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: null
  h2:
    console:
      enabled: true